---
title: "weather_data_script"
author: "Hannah Phillips"
date: "May 8, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F)

library(readxl)
library(tidyverse)
library(ggplot2)
library(ggsci)
library(lubridate)
library(cowplot)
```

Morris, MN weather data: https://wcroc.cfans.umn.edu/weather/weather-history
Reading, PA weather data (Station: USW00014712; READING REGIONAL AIRPORT, PA US): https://www.climate.gov/maps-data/dataset/past-weather-zip-code-data-table

```{r, include = F}
dat.MN <- 
  read_excel(
    "weather_data.xlsx", 
    sheet = "MN", 
    col_types = c("date", "numeric", "numeric", "numeric", "numeric")
    ) %>%
  mutate(Location = "Minnesota")

dat.PA <- 
  read_excel(
    "weather_data.xlsx", 
    sheet = "PA", 
    col_types = c("date", "numeric", "numeric", "numeric", "numeric")
    ) %>%
  mutate(Location = "Pennsylvania")

dat <- 
  rbind(dat.MN, dat.PA) %>%
  mutate(temp_high = (temp_high - 32)*5/9) %>%
  mutate(temp_low = (temp_low - 32)*5/9) %>%
  mutate(temp_avg = (temp_high + temp_low)/2) %>%
  mutate(rain_mm = rain_in * 25.4) %>%
  mutate(snow_mm = snow_in * 25.4) %>%
  mutate(Date = as.Date(Date)) %>%
  mutate(rain_mm = ifelse(rain_mm > 600, NA, rain_mm))

dat.rain <- 
  dat %>%
  group_by(Location, Date = floor_date(Date, "month")) %>%
  summarize(precip_sum = sum(rain_mm, na.rm = T)) %>%
  mutate(Date = as.Date(Date)) %>%
  ungroup(Location) %>%
  mutate(Location = as.factor(Location)) %>%
  mutate(Type = "Rainfall")

dat.snow <- 
  dat %>%
  group_by(Location, Date = floor_date(Date, "month")) %>%
  summarize(precip_sum = sum(snow_mm, na.rm = T)) %>%
  mutate(Date = as.Date(Date)) %>%
  ungroup(Location) %>%
  mutate(Location = as.factor(Location)) %>%
  mutate(Type = "Snowfall")

dat.precip <- rbind(dat.rain, dat.snow)
```

```{r, echo = F}
temp.plot <- 
  ggplot(dat, aes(Date, temp_avg, color = Location)) +
  geom_point(alpha = 0.2, show.legend = F) +
  geom_smooth(se = F) +
  scale_color_npg()+
  theme_bw() +
  labs(
    x = NULL, 
    y = "Average daily temperature, \u00B0C"
  ) +
  theme(
    legend.position = c(.5, .2),
    legend.direction = "vertical",
    plot.margin = margin(6, 0, 6, 0)
  ) +
  scale_x_date(
    date_labels = "%b-%y", 
    date_breaks = "3 months", 
    date_minor_breaks = "1 months",
    expand = c(0.02,0.02)
  ) 


precip.plot <- 
  ggplot(dat.precip, aes(Date, precip_sum, color = Location, linetype = Type)) +
  geom_point(alpha = 0.6, size = 2, show.legend = T, aes(shape = Type)) +
  geom_smooth(se = F) +
  scale_color_npg(guide = F) +
  theme_bw() +
  labs(
    x = "Date, month-year", 
    y = "Average total monthly precipitation, mm"
  ) +
  theme(
    legend.position = c(.5, .8),
    legend.direction = "vertical",
    plot.margin = margin(6, 0, 6, 0)
  ) +
  scale_x_date(
    date_labels = "%b-%y", 
    date_breaks = "3 months", 
    date_minor_breaks = "1 months",
    expand = c(0.02,0.02)
  ) +
  guides(lty = guide_legend(override.aes = list(col = 'darkgrey')))


plot <-
  cowplot::plot_grid(
    NULL,
    temp.plot + theme(legend.position = "none"), 
    NULL,
    precip.plot + theme(legend.position = "none"), 
    labels = c("A", "", "B", ""), 
    nrow = 2,
    ncol = 2,
    rel_widths = c(.05, 1),
    align = "hv") 

legend1 <- 
  get_legend(
    temp.plot + theme(legend.box.margin = margin(0, 0, 0, 12))
  )

legend2 <- 
  get_legend(
    precip.plot + theme(legend.box.margin = margin(0, 0, 0, 12))
  )


legend <- plot_grid(legend1, legend2, NULL, ncol = 1, align = "hv")

plot_grid(plot, legend, rel_widths = c(3, .4), align = "hv") +
  ggsave("weather_plot.png", width = 10, height = 7)
```




